name: Functional Tests

on:
  workflow_call:


jobs:
  functional-tests:
    strategy:
      fail-fast: false
      matrix:
        base: [noble, jammy]
    runs-on: [self-hosted, large, "${{ matrix.base }}", x64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt install --yes dpkg-dev libapt-pkg-dev keystone mysql-server placement-api glance-api tempest python3-tempestconf python3-openstackclient neutron-server neutron-ovn-metadata-agent openvswitch-switch ovn-central ovn-host nova-api nova-conductor nova-scheduler nova-compute nova-spiceproxy spice-html5 rabbitmq-server ceph-mgr ceph-mon ceph-osd ceph-volume cinder-api cinder-scheduler cinder-volume heat-api heat-api-cfn heat-engine heat-tempest-plugin

    - name: Install uv
      run: sudo snap install --classic astral-uv

    - name: Plan
      run: |
        sudo uv run regress-stack plan

    - name: Setup
      run: |
        sudo uv run regress-stack setup

    - name: Test
      run: |
        sudo uv run regress-stack test
